name: 🔁 Auto Update Profile README

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write  # ✅ gives permission to push changes

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README timestamp
        run: |
          echo "🕒 Updating timestamp..."
          DATE=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          sed -i "s|<!--LAST_UPDATED-->.*<!--END_LAST_UPDATED-->|<!--LAST_UPDATED--> Last updated: ${DATE} <!--END_LAST_UPDATED-->|" README.md || echo "No timestamp placeholder found."
          echo "✅ Done."

      - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "auto: update readme timestamp"
          git push
